ZB-ChalKak/chalKak-back

src/main/java/com/btb/chalKak/domain/post/entity/Post.java, src/main/java/com/btb/chalKak/domain/post/repository/PostRepository.java, src/main/java/com/btb/chalKak/domain/user/entity/User.java, src/main/java/com/btb/chalKak/domain/user/repository/UserRepository.java
#6 유저, 게시글 Entity, Repository 생성
=> 유저, 게시글 Entity, Repository

src/main/resources/application.yml, src/main/resources/table/h2/data.sql, src/main/resources/table/mySql/data.sql
=> 회원 및 정적태그 데이터 추가

src/main/java/com/btb/chalKak/domain/member/repository/MemberRepository.java, src/main/java/com/btb/chalKak/global/security/CustomUserDetails.java, src/main/java/com/btb/chalKak/global/security/CustomUserDetailsService.java
=> UserDetails, UserDetailsService 구현

src/main/java/com/btb/chalKak/domain/hashTag/entity/HashTag.java, src/main/java/com/btb/chalKak/domain/member/entity/Member.java, src/main/java/com/btb/chalKak/domain/post/entity/Post.java, src/main/java/com/btb/chalKak/domain/post/type/PostStatus.java, src/main/java/com/btb/chalKak/domain/styleTag/entity/StyleTag.java, src/main/java/com/btb/chalKak/domain/styleTag/type/StyleCategory.java, src/main/resources/table/h2/data.sql, src/main/resources/table/h2/schema.sql, src/main/resources/table/mySql/data.sql, src/main/resources/table/mySql/schema.sql
=> 게시물 작성을 위한 Entity 작업 추가

src/main/java/com/btb/chalKak/global/security/JwtTokenProvider.java, src/main/resources/application.yml
1. @Value 경로 부분 오타 수정
2. 시크릿 키를 충분히 긴 값으로 yml에서 변경
=> [#25] fix : 오타 및 시크릿 키 수정

src/main/java/com/btb/chalKak/domain/comment/controller/CommentController.java, src/main/java/com/btb/chalKak/domain/comment/dto/request/CreateCommentRequest.java, src/main/java/com/btb/chalKak/domain/comment/dto/request/DeleteCommentRequest.java, src/main/java/com/btb/chalKak/domain/comment/dto/request/ModifyCommentRequest.java, src/main/java/com/btb/chalKak/domain/comment/dto/response/CommentResponse.java, src/main/java/com/btb/chalKak/domain/comment/entity/Comment.java, src/main/java/com/btb/chalKak/domain/comment/repository/CommentRepository.java, src/main/java/com/btb/chalKak/domain/comment/service/CommentService.java, src/main/java/com/btb/chalKak/domain/comment/service/impl/CommentServiceImpl.java
[#31] 댓글 조회/생성/삭제/수정 기능 추가
- To do : Custome exception 기능으로 exception 처리 필요 및 토큰 검증 필요
=> [#31] comment 조회/생성/삭제/수정 기능

src/main/java/com/btb/chalKak/domain/comment/repository/CommentRepository.java, src/main/java/com/btb/chalKak/domain/comment/service/impl/CommentServiceImpl.java, src/test/java/com/btb/chalKak/domain/comment/service/impl/CommentServiceImplTest.java
#31 feat : comment 조회/생성/수정 Test 완료
=> [#31] feat : comment 조회/생성/수정 Test 완료

build.gradle, src/main/java/com/btb/chalKak/common/response/type/SuccessCode.java, src/main/java/com/btb/chalKak/domain/weather/controller/WeatherController.java, src/main/java/com/btb/chalKak/domain/weather/dto/WeatherDto.java, src/main/java/com/btb/chalKak/domain/weather/service/WeatherService.java, src/main/resources/application-oauth.yml
[#12] feat : 위도 경도에 따른 날씨 정보 api 구현
=> [#12] feat : openWeather로 날씨 정보 api 구현

src/main/java/com/btb/chalKak/common/response/type/SuccessCode.java, src/main/java/com/btb/chalKak/common/security/JwtAuthenticationFilter.java, src/main/java/com/btb/chalKak/common/security/JwtProvider.java, src/main/java/com/btb/chalKak/common/security/JwtTokenProvider.java, src/main/java/com/btb/chalKak/common/security/dto/TokenDto.java, src/main/java/com/btb/chalKak/common/security/entity/RefreshToken.java, src/main/java/com/btb/chalKak/common/security/provider/CustomAuthenticationProvider.java, src/main/java/com/btb/chalKak/common/security/repository/RefreshTokenRepository.java, src/main/java/com/btb/chalKak/common/security/request/TokenRequestDto.java, src/main/java/com/btb/chalKak/common/security/service/Impl/CustomUserDetailsService.java, src/main/java/com/btb/chalKak/domain/member/controller/SignController.java, src/main/java/com/btb/chalKak/domain/member/dto/request/SignInMemberRequest.java, src/main/java/com/btb/chalKak/domain/member/dto/request/SignUpMemberRequest.java, src/main/java/com/btb/chalKak/domain/member/dto/response/SignInMemberResponse.java, src/main/java/com/btb/chalKak/domain/member/entity/Member.java, src/main/java/com/btb/chalKak/domain/member/service/Impl/MemberServiceImpl.java, src/main/java/com/btb/chalKak/domain/member/service/MemberService.java, src/main/java/com/btb/chalKak/domain/styleTag/repository/StyleTagRepository.java, src/main/resources/application.yml, src/test/java/com/btb/chalKak/domain/member/service/Impl/MemberServiceImplTest.java
=> 회원가입, 로그인, 토큰 구현

build.gradle, src/main/java/com/btb/chalKak/ChalKakApplication.java, src/main/java/com/btb/chalKak/batch/TutorialTasklet.java, src/main/java/com/btb/chalKak/batch/exampleBatch.java, src/main/java/com/btb/chalKak/scheduler/BatchScheduler.java, src/main/java/com/btb/chalKak/scheduler/WeatherScheduler.java, src/main/resources/application.yml, src/main/resources/table/h2/schema.sql
#45 spring-batch 기본 설정 및 scheduler 구성
=> Feature/#45 spring-batch setting

src/main/java/com/btb/chalKak/common/response/type/SuccessCode.java, src/main/java/com/btb/chalKak/domain/follow/controller/FollowController.java, src/main/java/com/btb/chalKak/domain/follow/entity/Follow.java, src/main/java/com/btb/chalKak/domain/follow/repository/FollowRepository.java, src/main/java/com/btb/chalKak/domain/follow/service/FollowService.java, src/main/java/com/btb/chalKak/domain/like/entity/Like.java, src/test/java/com/btb/chalKak/domain/follow/service/FollowServiceTest.java
=> [#48] feat : follow 기능 구현

src/main/java/com/btb/chalKak/domain/follow/entity/Follow.java, src/main/java/com/btb/chalKak/domain/member/entity/Member.java, src/main/java/com/btb/chalKak/domain/member/type/MemberProvider.java, src/main/resources/table/h2/data.sql, src/main/resources/table/h2/schema.sql
#48  fix : follow entity 에러 수정
#41 feat : member provider add
=> [#41] feat : member provider 추가

src/main/java/com/btb/chalKak/common/oauth2/dto/OAuthAttributes.java, src/main/java/com/btb/chalKak/domain/member/service/Impl/MemberServiceImpl.java, src/main/resources/table/h2/schema.sql, src/main/resources/table/mySql/data.sql, src/main/resources/table/mySql/schema.sql
#41 
feat : member provider 검증 추가
fix : password not null schema 변경
=> [#41] feat : member provider 검증 추가

src/main/java/com/btb/chalKak/common/exception/MemberException.java, src/main/java/com/btb/chalKak/common/response/type/ErrorCode.java, src/main/java/com/btb/chalKak/common/response/type/SuccessCode.java, src/main/java/com/btb/chalKak/common/security/JwtAuthenticationFilter.java, src/main/java/com/btb/chalKak/common/security/JwtProvider.java, src/main/java/com/btb/chalKak/common/security/customUser/CustomUserDetails.java, src/main/java/com/btb/chalKak/common/security/customUser/CustomUserDetailsService.java, src/main/java/com/btb/chalKak/common/security/provider/CustomAuthenticationProvider.java, src/main/java/com/btb/chalKak/common/util/ValidationUtils.java, src/main/java/com/btb/chalKak/config/SecurityConfig.java, src/main/java/com/btb/chalKak/domain/member/controller/SignController.java, src/main/java/com/btb/chalKak/domain/member/dto/Writer.java, src/main/java/com/btb/chalKak/domain/member/dto/request/SignUpMemberRequest.java, src/main/java/com/btb/chalKak/domain/member/entity/Member.java, src/main/java/com/btb/chalKak/domain/member/service/Impl/MemberServiceImpl.java, src/main/java/com/btb/chalKak/domain/member/service/MemberService.java, src/main/java/com/btb/chalKak/domain/member/type/MemberStatus.java, src/main/resources/application.yml
=> 회원가입 로직 수정

src/main/java/com/btb/chalKak/common/oauth2/handler/OAuth2SuccessHandler.java
feat : OAuth2SuccessHandler 수정
=> [#43] feat : OAuth2SuccessHandler 수정

src/main/java/com/btb/chalKak/common/exception/PostException.java, src/main/java/com/btb/chalKak/domain/comment/controller/CommentController.java, src/main/java/com/btb/chalKak/domain/post/controller/PostController.java, src/main/java/com/btb/chalKak/domain/post/dto/request/WritePostRequest.java, src/main/java/com/btb/chalKak/domain/post/dto/response/LoadPublicPostDetailsResponse.java, src/main/java/com/btb/chalKak/domain/post/dto/response/LoadPublicPostsResponse.java, src/main/java/com/btb/chalKak/domain/post/dto/response/WritePostResponse.java, src/main/java/com/btb/chalKak/domain/post/entity/Post.java, src/main/java/com/btb/chalKak/domain/post/repository/PostRepository.java, src/main/java/com/btb/chalKak/domain/post/service/PostService.java, src/main/java/com/btb/chalKak/domain/post/service/impl/PostServiceImpl.java, src/main/java/com/btb/chalKak/domain/styleTag/entity/StyleTag.java, src/main/java/com/btb/chalKak/scheduler/PostScheduler.java, src/main/resources/table/h2/data.sql, src/main/resources/table/h2/schema.sql, src/main/resources/table/mySql/data.sql, src/main/resources/table/mySql/schema.sql, src/test/java/com/btb/chalKak/domain/comment/service/impl/CommentServiceImplTest.java, src/test/java/com/btb/chalKak/domain/post/service/impl/PostServiceImplTest.java
=> 게시판 기능 개발 (수정) 

src/main/java/com/btb/chalKak/common/exception/GlobalExceptionHandler.java, src/main/java/com/btb/chalKak/common/oauth2/handler/OAuth2SuccessHandler.java, src/main/java/com/btb/chalKak/common/security/entity/RefreshToken.java, src/main/java/com/btb/chalKak/common/security/service/Impl/TokenServiceImpl.java, src/main/java/com/btb/chalKak/domain/member/service/Impl/MemberServiceImpl.java, src/main/resources/table/h2/data.sql, src/main/resources/table/h2/schema.sql
=> 머지 후 충돌 해결

build.gradle
chore : aws service up / 설정 추가
=> chore : aws service up

.travis.yml
=> [#60] chore : travis 설정

travis.test1
[#60] test : travis build test2
=> [#60] test : travis build test2

build.gradle, src/main/java/com/btb/chalKak/config/SwaggerConfig.java
=> [#60] feat : swagger2  설정

src/main/resources/application.yml
=> [#60] fix : h2 외부 확인 설정

src/main/java/com/btb/chalKak/domain/post/dto/response/LoadPublicPostDetailsResponse.java, src/main/java/com/btb/chalKak/domain/post/service/PostService.java, src/main/java/com/btb/chalKak/domain/post/service/impl/PostServiceImpl.java
=> [#89] fix : 충돌 해결을 위한 커밋

src/main/java/com/btb/chalKak/domain/post/dto/response/LoadPublicPostDetailsResponse.java, src/main/java/com/btb/chalKak/domain/post/service/PostService.java, src/main/java/com/btb/chalKak/domain/post/service/impl/PostServiceImpl.java
Reverts ZB-ChalKak/chalKak-back#90
=> Revert "[#89] fix : 충돌 해결을 위한 커밋"

src/main/java/com/btb/chalKak/domain/post/service/impl/PostServiceImpl.java
=> [#96] fix : conflict fix

src/main/java/com/btb/chalKak/config/SecurityConfig.java
=> [#96] fix : oauth2

src/main/resources/application-oauth.yml
[#60] chore : oauth2 redirect-uri
=> [#60] chore : oauth2 redirect-uri

src/main/java/com/btb/chalKak/domain/comment/controller/CommentController.java, src/main/java/com/btb/chalKak/domain/comment/dto/response/LoadPageCommentsResponse.java, src/main/java/com/btb/chalKak/domain/comment/repository/CommentRepository.java, src/main/java/com/btb/chalKak/domain/comment/service/CommentService.java, src/main/java/com/btb/chalKak/domain/comment/service/impl/CommentServiceImpl.java, src/test/java/com/btb/chalKak/domain/comment/service/impl/CommentServiceImplTest.java
[#104] fix : comment pageable 기능 추가
=> [#104] fix : comment pageable 기능 추가

src/main/java/com/btb/chalKak/common/exception/type/ErrorCode.java, src/main/java/com/btb/chalKak/common/exception/type/SuccessCode.java, src/main/java/com/btb/chalKak/domain/follow/repository/FollowRepository.java, src/main/java/com/btb/chalKak/domain/member/controller/SignController.java, src/main/java/com/btb/chalKak/domain/member/dto/request/CheckPasswordRequest.java, src/main/java/com/btb/chalKak/domain/member/dto/response/SignInMemberResponse.java, src/main/java/com/btb/chalKak/domain/member/dto/response/UserDetailsInfoResponse.java, src/main/java/com/btb/chalKak/domain/member/dto/response/UserInfoResponse.java, src/main/java/com/btb/chalKak/domain/member/entity/Member.java, src/main/java/com/btb/chalKak/domain/member/service/Impl/MemberServiceImpl.java, src/main/java/com/btb/chalKak/domain/member/service/MemberService.java
=> 회원 정보 조회(토큰 O,X), 비밀 번호 체크

src/main/java/com/btb/chalKak/common/exception/type/SuccessCode.java, src/main/java/com/btb/chalKak/domain/member/controller/SignController.java, src/main/java/com/btb/chalKak/domain/member/service/Impl/MemberServiceImpl.java, src/main/java/com/btb/chalKak/domain/member/service/MemberService.java
=> 이메일, 닉네임 응답 값 수정

src/main/java/com/btb/chalKak/domain/member/controller/SignController.java, src/main/java/com/btb/chalKak/domain/member/dto/response/ValidateInfoResponse.java, src/main/java/com/btb/chalKak/domain/member/service/Impl/MemberServiceImpl.java, src/main/java/com/btb/chalKak/domain/member/service/MemberService.java
=> fix : 이메일, 닉네임 중복 체크 response 수정

src/main/java/com/btb/chalKak/common/exception/type/ErrorCode.java, src/main/java/com/btb/chalKak/common/exception/type/SuccessCode.java, src/main/java/com/btb/chalKak/domain/filter/controller/FilterController.java, src/main/java/com/btb/chalKak/domain/filter/service/FilterService.java, src/main/java/com/btb/chalKak/domain/filter/service/impl/FilterServiceImpl.java, src/main/java/com/btb/chalKak/domain/member/controller/SignController.java, src/main/java/com/btb/chalKak/domain/member/dto/request/ModifyUserInfoRequest.java, src/main/java/com/btb/chalKak/domain/member/entity/Member.java, src/main/java/com/btb/chalKak/domain/member/service/Impl/MemberServiceImpl.java, src/main/java/com/btb/chalKak/domain/member/service/MemberService.java
=> [#112] feature : 회원 정보 수정, 회원 탈퇴

src/main/java/com/btb/chalKak/common/exception/type/SuccessCode.java, src/main/java/com/btb/chalKak/domain/filter/controller/FilterController.java, src/main/java/com/btb/chalKak/domain/filter/dto/response/MemberFilterResponse.java, src/main/java/com/btb/chalKak/domain/filter/dto/response/PostFilterResponse.java, src/main/java/com/btb/chalKak/domain/filter/dto/response/TagFilterResponse.java, src/main/java/com/btb/chalKak/domain/filter/service/FilterService.java, src/main/java/com/btb/chalKak/domain/filter/service/impl/FilterServiceImpl.java, src/main/java/com/btb/chalKak/domain/filter/type/TagType.java, src/main/java/com/btb/chalKak/domain/hashTag/repository/HashTagRepository.java, src/main/java/com/btb/chalKak/domain/member/repository/MemberRepository.java, src/main/java/com/btb/chalKak/domain/post/repository/PostRepository.java, src/main/java/com/btb/chalKak/domain/styleTag/repository/StyleTagRepository.java
=> [#114] feature : 검색 기능 기본 구현

src/main/java/com/btb/chalKak/domain/comment/dto/response/CommentLoadResponse.java, src/main/java/com/btb/chalKak/domain/comment/dto/response/LoadPageCommentsResponse.java
[#31] fix : CommentLoadResponse memberId 추가
=> [#31] fix : CommentLoadResponse memberId 추가

src/main/java/com/btb/chalKak/common/oauth2/handler/OAuth2SuccessHandler.java
=> [#104] feat : cookie 추가

src/main/java/com/btb/chalKak/domain/comment/repository/CommentRepository.java, src/main/java/com/btb/chalKak/domain/comment/service/impl/CommentServiceImpl.java
=> [#31] fix : comment 삭제 로직

src/main/java/com/btb/chalKak/scheduler/WeatherScheduler.java
=> [#12] fix : scheduler 주기 재설정

src/main/java/com/btb/chalKak/domain/weather/service/Impl/WeatherServiceImpl.java, src/main/java/com/btb/chalKak/scheduler/WeatherScheduler.java
=> [#12] fix : weather 불필요 로그 삭제

src/main/java/com/btb/chalKak/domain/member/service/Impl/MemberServiceImpl.java, src/main/java/com/btb/chalKak/scheduler/WeatherScheduler.java
=> [#12] fix : build error 수정

build.gradle, src/main/java/com/btb/chalKak/common/exception/type/SuccessCode.java, src/main/java/com/btb/chalKak/domain/filter/controller/FilterController.java, src/main/java/com/btb/chalKak/domain/filter/dto/response/TagFilterResponse.java, src/main/java/com/btb/chalKak/domain/filter/service/FilterService.java, src/main/java/com/btb/chalKak/domain/filter/service/impl/FilterServiceImpl.java, src/main/java/com/btb/chalKak/domain/member/controller/SignController.java, src/main/java/com/btb/chalKak/domain/member/dto/request/ModifyPasswordRequest.java, src/main/java/com/btb/chalKak/domain/member/dto/request/ModifyUserInfoRequest.java, src/main/java/com/btb/chalKak/domain/member/dto/response/SignInMemberResponse.java, src/main/java/com/btb/chalKak/domain/member/entity/Member.java, src/main/java/com/btb/chalKak/domain/member/service/Impl/MemberServiceImpl.java, src/main/java/com/btb/chalKak/domain/member/service/MemberService.java
=> [#139] fix : Member, Filter 수정

src/main/java/com/btb/chalKak/domain/filter/controller/FilterController.java, src/main/java/com/btb/chalKak/domain/filter/dto/response/MemberFilterResponse.java, src/main/java/com/btb/chalKak/domain/filter/service/FilterService.java, src/main/java/com/btb/chalKak/domain/filter/service/impl/FilterServiceImpl.java, src/main/java/com/btb/chalKak/domain/hashTag/repository/HashTagRepository.java, src/main/java/com/btb/chalKak/domain/member/repository/MemberRepository.java, src/main/java/com/btb/chalKak/domain/post/repository/PostRepository.java, src/main/java/com/btb/chalKak/domain/styleTag/repository/StyleTagRepository.java
=> [#139] fix : Filter Pageable 구현

src/main/java/com/btb/chalKak/domain/filter/service/impl/FilterServiceImpl.java
=> [#139] fix : Filter sort

src/main/java/com/btb/chalKak/domain/filter/service/impl/FilterServiceImpl.java
=> [#139] fix : fix sort

src/main/java/com/btb/chalKak/domain/filter/service/impl/FilterServiceImpl.java
=> [#139] fix : rebase filter

src/main/java/com/btb/chalKak/domain/member/controller/SignController.java, src/main/java/com/btb/chalKak/domain/member/dto/request/ModifyPasswordRequest.java
=> [#139] fix : password modify

src/main/java/com/btb/chalKak/common/exception/type/SuccessCode.java, src/main/java/com/btb/chalKak/domain/member/dto/response/CheckPasswordResponse.java
=> [#148] fix : checkPassword etc

src/main/java/com/btb/chalKak/common/oauth2/handler/OAuth2SuccessHandler.java, src/main/java/com/btb/chalKak/common/oauth2/service/CustomOAuth2UserService.java
[#12] fix : success handler redirect 수정
=> [#12] fix : success handler redirect 수정

src/main/java/com/btb/chalKak/domain/like/service/LikeService.java, src/main/java/com/btb/chalKak/domain/member/controller/SignController.java, src/main/java/com/btb/chalKak/domain/member/service/Impl/MemberServiceImpl.java, src/main/java/com/btb/chalKak/domain/member/service/MemberService.java, src/main/java/com/btb/chalKak/domain/post/dto/response/LoadUserPublicPostPreviewResponse.java, src/main/java/com/btb/chalKak/domain/post/dto/response/LoadUserPublicPostsResponse.java
=> 회원 게시글 조회 로직 수정

src/main/java/com/btb/chalKak/common/exception/type/ErrorCode.java, src/main/java/com/btb/chalKak/common/oauth2/handler/OAuth2SuccessHandler.java, src/main/java/com/btb/chalKak/domain/member/dto/response/SignInMemberResponse.java, src/main/java/com/btb/chalKak/domain/member/dto/response/UserDetailsInfoResponse.java, src/main/java/com/btb/chalKak/domain/member/service/Impl/MemberServiceImpl.java
=> [#148] fix : SignInMemberResponse, UserDetailsInfoResponse

src/main/java/com/btb/chalKak/domain/post/service/impl/PostServiceImpl.java
=> [#162] fix : 게시글 수정시 이미지 삭제되지 않는 기능 수정

src/main/java/com/btb/chalKak/domain/member/service/Impl/MemberServiceImpl.java, src/main/java/com/btb/chalKak/domain/member/service/MemberService.java
=> [#148] follower, following count가 서로 뒤바뀌어 있는 문제 수정 + refactor

src/main/java/com/btb/chalKak/domain/member/controller/SignController.java
=> [#148] refactor : memberService -> authentication

src/main/java/com/btb/chalKak/domain/member/dto/response/UserDetailsInfoResponse.java, src/main/java/com/btb/chalKak/domain/member/service/Impl/MemberServiceImpl.java
=> [#148] userDetailsInfoResponse 닉네임 추가

src/main/java/com/btb/chalKak/domain/like/service/LikeService.java, src/main/java/com/btb/chalKak/domain/post/controller/PostController.java, src/main/java/com/btb/chalKak/domain/post/service/impl/PostServiceImpl.java
=> 리팩토링(좋아요, 게시글 수정)

src/main/java/com/btb/chalKak/common/oauth2/handler/OAuth2SuccessHandler.java, src/main/java/com/btb/chalKak/common/security/dto/TokenReissueResponse.java, src/main/java/com/btb/chalKak/common/security/jwt/JwtProvider.java, src/main/java/com/btb/chalKak/common/security/request/TokenReissueRequest.java, src/main/java/com/btb/chalKak/domain/member/controller/SignController.java, src/main/java/com/btb/chalKak/domain/member/dto/response/SignInMemberResponse.java, src/main/java/com/btb/chalKak/domain/member/dto/response/UserInfoResponse.java, src/main/java/com/btb/chalKak/domain/member/service/Impl/MemberServiceImpl.java, src/main/java/com/btb/chalKak/domain/member/service/MemberService.java
=> [#148] fix : memberService -> reissue, UserInfoResponse

src/main/java/com/btb/chalKak/domain/like/service/LikeService.java, src/main/java/com/btb/chalKak/domain/post/entity/Post.java
[#175] feat : like 추가 시 post count++
=> [#175] feat : like 추가시 post count++

src/main/java/com/btb/chalKak/batch/BatchConfiguration.java, src/main/java/com/btb/chalKak/batch/listener/TableClearingListener.java, src/main/java/com/btb/chalKak/batch/processor/PostItemProcessor.java, src/main/java/com/btb/chalKak/batch/reader/PostItemReader.java, src/main/java/com/btb/chalKak/batch/writer/RecommendPostItemWriter.java, src/main/java/com/btb/chalKak/domain/batchpost/entity/RecommendPostBatch.java, src/main/java/com/btb/chalKak/domain/batchpost/repository/RecommendPostBatchRepository.java, src/main/java/com/btb/chalKak/domain/post/entity/Post.java, src/main/java/com/btb/chalKak/domain/post/repository/PostRepository.java, src/main/java/com/btb/chalKak/domain/styleTag/entity/StyleTag.java, src/main/java/com/btb/chalKak/domain/weather/service/Impl/WeatherServiceImpl.java, src/main/java/com/btb/chalKak/scheduler/BatchScheduler.java, src/main/resources/application.yml, src/test/java/com/btb/chalKak/domain/batchpost/repository/RecommendPostBatchRepositoryTest.java
[#45] feat : batch reader/processor/writer
writer saveAll 수정 필요
=> [#45] feat : batch reader/processor/writer

src/main/java/com/btb/chalKak/domain/batchpost/entity/RecommendPostBatch.java, src/main/java/com/btb/chalKak/domain/weather/service/Impl/WeatherServiceImpl.java
[#45] fix : weather post aws test
=> [#45] fix : weather post aws test

src/main/java/com/btb/chalKak/domain/weather/service/Impl/WeatherServiceImpl.java
=> [#45] fix : log up

src/main/java/com/btb/chalKak/common/exception/type/ErrorCode.java, src/main/java/com/btb/chalKak/domain/weather/repository/WeatherRepository.java, src/main/java/com/btb/chalKak/domain/weather/service/Impl/WeatherServiceImpl.java
[#45] fix : weather Exception add
=> [#45] fix : weather Exception add

src/main/java/com/btb/chalKak/domain/comment/service/impl/CommentServiceImpl.java, src/main/java/com/btb/chalKak/domain/weather/service/Impl/WeatherServiceImpl.java
[#45] fix : today string log 추가
=> [#45] fix : today string log 추가

src/main/java/com/btb/chalKak/domain/weather/repository/WeatherRepository.java, src/main/java/com/btb/chalKak/domain/weather/service/Impl/WeatherServiceImpl.java
[#45] fix : today string log 추가, repository geo 수정
=> [#45] fix : today string log 추가, repository geo 수정

src/main/java/com/btb/chalKak/domain/weather/repository/WeatherRepository.java, src/main/java/com/btb/chalKak/domain/weather/service/Impl/WeatherServiceImpl.java
[#45] fix : date-format-to-string
=> [#45] fix : date-format-to-string

src/main/java/com/btb/chalKak/domain/weather/service/Impl/WeatherServiceImpl.java
=> [#45] fix : log-delete

src/main/java/com/btb/chalKak/domain/batchpost/service/RecommendPostBatchService.java, src/main/java/com/btb/chalKak/domain/post/repository/PostRepository.java, src/main/java/com/btb/chalKak/domain/weather/service/Impl/WeatherServiceImpl.java, src/test/java/com/btb/chalKak/domain/batchpost/service/RecommendPostBatchServiceTest.java
=> [#12] feat : RecommendPostBatchService 구현

src/main/java/com/btb/chalKak/domain/member/service/Impl/MemberServiceImpl.java, src/main/java/com/btb/chalKak/domain/post/dto/response/LoadPublicPostDetailsResponse.java, src/main/java/com/btb/chalKak/domain/post/repository/CustomPostRepository.java, src/main/java/com/btb/chalKak/domain/post/repository/impl/CustomPostRepositoryImpl.java, src/main/java/com/btb/chalKak/domain/post/service/impl/PostServiceImpl.java
=> 23.09.09 피드백 이후 리팩토링 (머지)

src/main/java/com/btb/chalKak/domain/photo/service/PhotoService.java
[#12] feat : bucket 지역 서울로 수정 -  페이지 속도 개선
=> [#12] feat : bucket 지역 서울로 수정

src/main/java/com/btb/chalKak/domain/post/repository/PostRepository.java
[#12] fix : weather post (p.status = 'PUBLIC' 추가) 수정
=> [#12] fix : weather post (p.status = 'PUBLIC' 추가) 수정

src/main/java/com/btb/chalKak/batch/processor/PostItemProcessor.java, src/main/java/com/btb/chalKak/batch/writer/RecommendPostItemWriter.java, src/main/java/com/btb/chalKak/common/exception/type/ErrorCode.java, src/main/java/com/btb/chalKak/domain/batchpost/entity/RecommendPostBatch.java, src/main/java/com/btb/chalKak/domain/batchpost/service/RecommendPostBatchService.java, src/main/java/com/btb/chalKak/domain/post/entity/Post.java, src/main/java/com/btb/chalKak/domain/post/repository/PostRepository.java, src/main/java/com/btb/chalKak/domain/weather/service/Impl/WeatherServiceImpl.java, src/main/java/com/btb/chalKak/scheduler/BatchScheduler.java
=> [#12] fix : weather fix

src/main/java/com/btb/chalKak/batch/BatchConfiguration.java, src/main/java/com/btb/chalKak/batch/listener/TableClearingListener.java, src/main/java/com/btb/chalKak/batch/processor/PostItemProcessor.java, src/main/java/com/btb/chalKak/batch/reader/PostItemReader.java, src/main/java/com/btb/chalKak/batch/writer/RecommendPostItemWriter.java, src/main/java/com/btb/chalKak/common/oauth2/handler/OAuth2SuccessHandler.java, src/main/java/com/btb/chalKak/domain/batchpost/dto/RecommendPostBatchDTO.java, src/main/java/com/btb/chalKak/domain/batchpost/entity/RecommendPostBatch.java, src/main/java/com/btb/chalKak/domain/batchpost/repository/RecommendPostBatchRepository.java, src/main/java/com/btb/chalKak/domain/post/dto/PostRecommendDto.java, src/main/java/com/btb/chalKak/domain/post/entity/Post.java, src/main/java/com/btb/chalKak/domain/post/repository/PostRepository.java
[#12] feat : batch 구조 완성, 첫번째 청크에서 지연로딩이 발생하지 않지만 두번째 청크에서는 지연 로딩이 발생
(임시 방편으로 chunk size를 늘려 지연로딩 무시)
=> [#12] feat : batch 구조 완성, 첫번째 청크에서 지연로딩이 발생하지 않지만

src/main/java/com/btb/chalKak/batch/BatchConfiguration.java, src/main/java/com/btb/chalKak/batch/JpaItemWriterJobConfiguration.java, src/main/java/com/btb/chalKak/batch/listener/TableClearingListener.java, src/main/java/com/btb/chalKak/domain/batchpost/entity/RecommendPostBatch.java, src/main/java/com/btb/chalKak/domain/batchpost/repository/RecommendPostBatchRepository.java, src/main/java/com/btb/chalKak/domain/weather/service/Impl/WeatherServiceImpl.java, src/main/java/com/btb/chalKak/scheduler/BatchScheduler.java, src/main/resources/application.yml
jpa-spring-batch 설정 후 post 추천 로직 변경
=> [#12] fix : jpa-spring-batch 설정 후 post 추천 로직 변경

src/main/java/com/btb/chalKak/domain/batchpost/repository/RecommendPostBatchRepository.java
(p.viewCount * 0.4 + p.likeCount * 0.6) DESC
=> [#12] fix : weather post 정렬

src/main/java/com/btb/chalKak/scheduler/WeatherScheduler.java
jpa-spring-batch 설정 후 post 추천 로직 변경
=> [#12] fix : 지역별 테이블 추가로 인해 query 급증하여

src/main/java/com/btb/chalKak/scheduler/WeatherScheduler.java
=> [#12] fix : 스케쥴러 bug 수정

src/main/java/com/btb/chalKak/domain/weather/service/Impl/WeatherServiceImpl.java, src/main/java/com/btb/chalKak/scheduler/WeatherScheduler.java
=> #12 chore : 기본 코드 삭제

src/main/java/com/btb/chalKak/domain/member/service/Impl/MemberServiceImpl.java
=> [#221] fix profileImg upload bug
